
Total GPUS: 8
Traceback (most recent call last):
  File "/home/yhzhang/LongMamba/train.py", line 60, in main
    train_dataset = load_dataset(args.dataset)
  File "/home/yhzhang/miniconda3/envs/mamba/lib/python3.10/site-packages/datasets/load.py", line 2523, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/yhzhang/miniconda3/envs/mamba/lib/python3.10/site-packages/datasets/load.py", line 2195, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/yhzhang/miniconda3/envs/mamba/lib/python3.10/site-packages/datasets/load.py", line 1840, in dataset_module_factory
    raise e1 from None
  File "/home/yhzhang/miniconda3/envs/mamba/lib/python3.10/site-packages/datasets/load.py", line 1783, in dataset_module_factory
    raise DatasetNotFoundError(msg + f" at revision '{revision}'" if revision else msg)
datasets.exceptions.DatasetNotFoundError: Dataset 'tokenized_slim6B_train_neox_4096' doesn't exist on the Hub
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/yhzhang/LongMamba/train.py", line 181, in <module>
    main(args.parse_args())
  File "/home/yhzhang/LongMamba/train.py", line 62, in main
    train_dataset = load_from_disk(args.dataset)
  File "/home/yhzhang/miniconda3/envs/mamba/lib/python3.10/site-packages/datasets/load.py", line 2630, in load_from_disk
    raise FileNotFoundError(f"Directory {dataset_path} not found")
FileNotFoundError: Directory tokenized_slim6B_train_neox_4096 not found